import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import ClientAuth from "./clientAuthenticated";
import type { Metadata } from "next";
/* eslint-disable @next/next/no-page-custom-font */
import StoreProvider from "@/redux/storeProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Barracão saas",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Noto+Rashi+Hebrew&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <StoreProvider>
                    <ClientAuth>{children}</ClientAuth>
                </StoreProvider>
            </body>
        </html>
    );
}
