/* eslint-disable @next/next/no-page-custom-font */
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { AppSidebar } from "@/components/common/app-sidebar.component";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { LoginPage } from "./login/login.page";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Barracão saas",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    let isLoged: boolean = false;

    const setLoged = () => {
        isLoged = true;
    }

    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Noto+Rashi+Hebrew&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <>
                    {isLoged && <SidebarProvider>
                        <AppSidebar />
                        <main className="flex w-full h-screen">
                            {/*<SidebarProvider/>*/}
                            <div className="flex-grow h-screen p-3">{children}</div>
                        </main>
                    </SidebarProvider>}

                    {!isLoged && <LoginPage userLoged={() => { }} />}
                </>
            </body>
        </html>
    );
}
